org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# The Minecraft version must agree with the NeoForge version to get a valid artifact
minecraft_version=1.21.1
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.21.1,1.22)

# The NeoForge version must agree with the Minecraft version to get a valid artifact
# See https://projects.neoforged.net/neoforged/neoforge for available versions
neo_version=21.1.84
# The NeoForge version range can use any version of NeoForge as bounds
neo_version_range=[21.1,)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[4,)

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
mod_id=teamlapenfaction2luckpermsgroup
# The human-readable display name for the mod.
mod_name=TeamlapenFaction2LuckpermsGroup
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=1.0-SNAPSHOT
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
mod_group_id=com.lunofe
# The authors of the mod.
mod_authors=lunofe
# The description of the mod.
mod_description=
